import {Component, inject} from '@angular/core';
import {EventService} from '../../../../core/services/event-service';
import {Event, EventStatus} from '../../../../core/models/events';
import {AuthService} from '../../../../core/services/auth-service';
import {EventFormService} from '../../../../core/services/event-form-service';


@Component({
  selector: 'app-create-event',
  standalone: false,
  templateUrl: './create-event.html',
  styleUrl: './create-event.css',
})

export class CreateEvent { //ID is not added here, because it's automatically generated by the system
  eventFormService = inject(EventFormService);
  newEventForm = this.eventFormService.createForm();

  eventService = inject(EventService);
  authService = inject(AuthService);
  onSubmit() {
    const newEvent :Event = this.eventFormService.fillEventFromForm(this.newEventForm,EventStatus.Published,this.eventService.getNextID(),this.authService.currentUser!.username)
    this.eventService.addEvent(newEvent); //temporary solution, ideally we'd POST
//Also need to add a function for the draft state. Maybe a seperate button or a preview page where it's automatically saved as a draft and change as published when the publish button is pressed
    console.log(newEvent);
    this.newEventForm.reset();}
  saveDraft(){
    const newEvent :Event = this.eventFormService.fillEventFromForm(this.newEventForm,EventStatus.Draft,this.eventService.getNextID(),this.authService.currentUser!.username);
    this.eventService.addEvent(newEvent);
    console.log(newEvent);
  }

  hasError(controlName: string, errorName: string): boolean {
    const control = this.newEventForm.get(controlName);

    return !!(
      control?.errors?.[errorName] &&
      control.touched
    );
  }
}
