import { Component, inject } from '@angular/core';
import {
  AbstractControl,
  FormControl,
  FormGroup,
  ValidationErrors,
  Validators,
} from '@angular/forms';
import { Router } from '@angular/router';
import { EventService, EventPayload } from '../../../../core/services/event-service';

export function dateRangeValidator(control: AbstractControl): ValidationErrors | null {
  const start = control.get('startDateTime')?.value;
  const end = control.get('endDateTime')?.value;

  if (!start || !end) {
    // if one of the dates is null -> return null (no error)
    return null;
  }
  if (new Date(start) >= new Date(end)) {
    return { invalidDateRange: true };
  }
  return null;
}

export function whitespaceValidator(control: AbstractControl): ValidationErrors | null {
  const value = control.value;
  if (!value) {
    return null;
  }
  return value.trim() === '' ? { isOnlyWhitespace: true } : null;
}

@Component({
  selector: 'app-create-event',
  standalone: false,
  templateUrl: './create-event.html',
  styleUrl: './create-event.css',
})
export class CreateEvent {
  // ID is not added here, because it's automatically generated by the system.
  private eventService = inject(EventService);
  private router = inject(Router);

  newEventForm = new FormGroup(
    {
      name: new FormControl('', [Validators.required, whitespaceValidator]),
      description: new FormControl('', [Validators.required, whitespaceValidator]),
      venue: new FormControl('', [Validators.required, whitespaceValidator]),
      address: new FormControl('', [Validators.required, whitespaceValidator]),
      city: new FormControl('', [Validators.required, whitespaceValidator]),
      country: new FormControl('', [Validators.required, whitespaceValidator]),
      startDateTime: new FormControl('', Validators.required),
      endDateTime: new FormControl('', Validators.required),
      capacity: new FormControl('', [Validators.required, Validators.min(1)]),
    },
    {
      validators: dateRangeValidator,
    },
  );

  onSubmit() {
    if (this.newEventForm.invalid) {
      return;
    }

    const raw = this.newEventForm.value;
    const payload: EventPayload = {
      name: raw.name!,
      description: raw.description!,
      venue: raw.venue!,
      address: raw.address!,
      city: raw.city!,
      country: raw.country!,
      startDateTime: raw.startDateTime!,
      endDateTime: raw.endDateTime!,
      capacity: Number(raw.capacity),
    };

    // Requires a logged-in user (the JWT identifies the organizer). Once the
    // auth/token flow + HTTP interceptor are wired, this will succeed; without
    // a token the backend responds 401.
    this.eventService.createEvent(payload).subscribe({
      next: () => this.router.navigate(['/manage-events']),
      error: (err) => console.error('Failed to create event', err),
    });
  }

  hasError(controlName: string, errorName: string): boolean {
    const control = this.newEventForm.get(controlName);
    return !!(control?.errors?.[errorName] && control.touched);
  }
}
