import { Component } from '@angular/core';
import {AbstractControl, FormControl, FormGroup, ValidationErrors, Validators} from '@angular/forms';


export function dateRangeValidator(control :AbstractControl): ValidationErrors | null {
  const start = control.get('startDateTime')?.value;
  const end = control.get('endDateTime')?.value;

  if (!start || !end){ //if one of the dates is null -> return null( no error)
    return null;
  }
  if(new Date(start) >= new Date(end)) {
    return {invalidDateRange: true};
  }
  return null;
}
export function whitespaceValidator(control: AbstractControl): ValidationErrors | null {
  const value = control.value;
  if (!value){
    return null;
  }
  return value.trim() === ''
    ? { isOnlyWhitespace: true }
    : null;
}

@Component({
  selector: 'app-create-event',
  standalone: false,
  templateUrl: './create-event.html',
  styleUrl: './create-event.css',
})

export class CreateEvent { //ID is not added here, because it's automatically generated by the system
  newEventForm = new FormGroup({
    name: new FormControl('',[Validators.required,whitespaceValidator]),
    description: new FormControl('',[Validators.required,whitespaceValidator]),
    venue: new FormControl('',[Validators.required,whitespaceValidator]),
    address: new FormControl('',[Validators.required,whitespaceValidator]),
    city: new FormControl('',[Validators.required,whitespaceValidator]),
    country: new FormControl('',[Validators.required,whitespaceValidator]),
    startDateTime: new FormControl('',Validators.required), //It'd be nice to have a validator where it checks whether the TIME is needed and say that only.
    endDateTime: new FormControl('',Validators.required),
    capacity: new FormControl('',[Validators.required,Validators.min(1)]),
  },{
    validators: dateRangeValidator
}); //more validators to be added

  onSubmit() {
    console.log(this.newEventForm.value); //temporary, need to connect to backend
  }
  hasError(controlName: string, errorName: string): boolean {
    const control = this.newEventForm.get(controlName);

    return !!(
      control?.errors?.[errorName] &&
      control.touched
    );
  }
}
